version: '3.7'
services:
  mysql-endpoint:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Root password for MySQL (for administrative access)
      MYSQL_DATABASE: ${MYSQL_DATABASE}           # Database to create
      MYSQL_USER: ${MYSQL_USER}                   # Non-root user for MySQL
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}           # Non-root user's password for authentication
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    environment:
      DB_HOST: ${BACKEND_DB_HOST}                  # MySQL container name (used by backend to connect to MySQL)
      DB_USER: ${BACKEND_DB_USER}                  # Non-root MySQL user (used by backend to connect to MySQL)
      DB_PASSWORD: ${BACKEND_DB_PASSWORD}          # Non-root MySQL user password (used by backend to connect to MySQL)
      DB_NAME: ${BACKEND_DB_NAME}                  # MySQL database name (used by backend to connect to MySQL)
      BACKEND_URL: "http://${EC2_PUBLIC_IP}:5000"  # Backend URL (set dynamically or manually with EC2 public IP)
    depends_on:
      - mysql-endpoint 
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: "http://${EC2_PUBLIC_IP}/api/data"  # Use proxied path
    ports:
      - "80:80"

volumes:
  db-data:

